import { FlagGame } from './game.js';
import { applyLanguage, getLanguage, t, setLanguage } from './i18n.js';
import { verifyPostingKey } from './steem-auth.js';
import { saveGameResult } from './reward.js?v=20260825-d1-game-01';
import { loadMenu } from './menu.js?v=20260825-menu-03';

const API_BASE = 'https://steemflags.mehdiq.workers.dev';
const SESSION_KEY = 'steemFlagsAuthSession';
const $ = id => document.getElementById(id);

async function loadComponent() { const response = await fetch('./components/app-shell.html?v=20260825-leaderboard-avatar-01', { cache: 'no-store' }); if (!response.ok) throw new Error(`Unable to load component: ${response.status}`); return response.text(); }
async function fetchAccount(username) { let response; try { response = await fetch(`${API_BASE}/api/account?username=${encodeURIComponent(username)}`, { cache: 'no-store' }); } catch { throw new Error('ACCOUNT_NETWORK_ERROR'); } if (!response.ok) throw new Error(`ACCOUNT_API_${response.status}`); const data = await response.json(); if (!data?.success || !data.account) throw new Error('ACCOUNT_API_INVALID'); return data.account; }
async function fetchAccounts(limit = 100) { const response = await fetch(`${API_BASE}/api/accounts?limit=${limit}`, { cache: 'no-store' }); if (!response.ok) throw new Error(`LEADERBOARD_API_${response.status}`); const data = await response.json(); if (!data?.success || !Array.isArray(data.accounts)) throw new Error('LEADERBOARD_API_INVALID'); return data.accounts; }
async function startGameOnServer(username) { const response = await fetch(`${API_BASE}/api/game/start`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username }), cache: 'no-store' }); const data = await response.json(); if (!response.ok || !data?.success) throw new Error(data?.error || `GAME_START_${response.status}`); return data.account; }
async function fetchSteemBalance(account) { const body = JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'condenser_api.get_accounts', params: [[account]] }); for (const endpoint of ['https://api.steemit.com', 'https://api.steem.house', 'https://api.steemyy.com']) { try { const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body, cache: 'no-store' }); if (!response.ok) continue; const data = await response.json(); const balance = data?.result?.[0]?.balance; if (typeof balance === 'string' && /\d/.test(balance)) return balance.replace(/\s*STEEM\s*$/i, '').trim(); } catch (error) { console.warn('STEEM endpoint failed', endpoint, error); } } return null; }
function readSession() { try { const value = localStorage.getItem(SESSION_KEY); if (!value) return null; const parsed = JSON.parse(value); return /^[a-z0-9.-]{3,32}$/.test(parsed?.username || '') ? parsed.username : null; } catch { return null; } }
function writeSession(username) { localStorage.setItem(SESSION_KEY, JSON.stringify({ username })); }
function clearSession() { localStorage.removeItem(SESSION_KEY); }

async function bootstrap() { const app = $('app'); if (!app) throw new Error('APP_CONTAINER_MISSING'); app.innerHTML = await loadComponent(); await loadMenu(); start(); }

function start() {
  let username = null, postingKey = null, account = null; let gameScore = 0, sessionQuestions = 0, sessionCorrect = 0;
  const loginView = $('loginView'), home = $('homeView'), leaderboard = $('leaderboardSection'), gameView = $('gameView'); const answers = $('answers'), feedback = $('feedback'), next = $('nextButton'); const energy = $('energyValue'), d2e = $('sfValue'), steem = $('steemValue'), assets = $('assetStats'); const counter = $('questionCounter'), score = $('scoreLabel'), flag = $('flagImage'); const newButton = $('newGameButton'), resumeButton = $('resumeGameButton'), summary = $('progressSummary'); const loginForm = $('loginForm'), usernameInput = $('usernameInput'), loginFeedback = $('loginFeedback'); const loggedIn = $('loggedInUser'), language = $('languageSelect'), progressBar = $('quizProgressBar'), info = $('countryInfoLink'); const leaderboardBody = $('leaderboardBody'), leaderboardStatus = $('leaderboardStatus');
  if (!loginForm || !loginView || !home || !gameView || !newButton || !leaderboardBody || !leaderboardStatus) throw new Error('REQUIRED_UI_MISSING'); const key = $('postingKeyInput'); if (!key) throw new Error('POSTING_KEY_INPUT_MISSING'); const game = new FlagGame(renderQuestion);
  function getLogoutButton() { return document.querySelector('[data-action="logout"]'); } function setLogoutVisible(visible) { const button = getLogoutButton(); if (button) button.hidden = !visible; } function hideInfo() { if (!info) return; info.hidden = true; info.removeAttribute('href'); info.style.display = 'none'; } function showInfo(name) { if (!info) return; const lang = getLanguage(); const host = lang === 'fa' ? 'fa' : lang === 'es' ? 'es' : 'en'; info.textContent = 'ℹ️ More information about this country'; info.href = `https://${host}.wikipedia.org/wiki/${encodeURIComponent(String(name).trim().replace(/ /g, '_'))}`; info.hidden = false; info.style.display = 'block'; }
  function bindLogout() { const button = getLogoutButton(); if (!button || button.dataset.bound === '1') return; button.dataset.bound = '1'; button.addEventListener('click', event => { event.preventDefault(); clearSession(); username = null; postingKey = null; account = null; game.reset(); gameScore = 0; sessionQuestions = 0; sessionCorrect = 0; loginForm.reset(); loginFeedback.textContent = ''; loginView.hidden = false; home.hidden = true; leaderboard.hidden = true; gameView.hidden = true; setLogoutVisible(false); hideInfo(); }); }
  function applyAccountToUI() { if (!account) return; energy.textContent = String(Number(account.Energy) || 0); d2e.textContent = String(Number(account.D2E) || 0); newButton.disabled = Number(account.Energy) <= 0; }
  async function renderLeaderboard() { leaderboardStatus.textContent = 'Loading leaderboard…'; leaderboardBody.replaceChildren(); try { const accounts = await fetchAccounts(100); accounts.forEach((item, index) => { const row = document.createElement('tr'); const rank = document.createElement('td'); const name = document.createElement('td'); const value = document.createElement('td'); const userWrap = document.createElement('div'); const avatar = document.createElement('img'); const usernameText = document.createElement('span'); rank.textContent = String(index + 1); userWrap.className = 'leaderboardUser'; avatar.className = 'leaderboardAvatar'; avatar.src = `https://steemitimages.com/u/${encodeURIComponent(item.Username)}/avatar`; avatar.alt = `${item.Username} avatar`; avatar.loading = 'lazy'; avatar.referrerPolicy = 'no-referrer'; avatar.onerror = () => { avatar.onerror = null; avatar.src = 'https://steemitimages.com/u/steem/avatar'; }; usernameText.className = 'leaderboardUsername'; usernameText.textContent = `@${item.Username}`; userWrap.append(avatar, usernameText); name.appendChild(userWrap); value.className = 'leaderboardD2E'; value.textContent = `${Number(item.D2E) || 0} D2E`; row.append(rank, name, value); leaderboardBody.appendChild(row); }); leaderboardStatus.textContent = accounts.length ? '' : 'No players yet.'; } catch (error) { console.error('Leaderboard load failed', error); leaderboardStatus.textContent = 'Unable to load leaderboard. Please refresh the page.'; } }
  async function syncAccountFromD1() { if (!username) return null; account = await fetchAccount(username); applyAccountToUI(); if (assets) assets.hidden = false; if (summary) summary.hidden = false; if (loggedIn) loggedIn.textContent = `${t('loggedInAs')} @${username}`; if (resumeButton) resumeButton.hidden = true; const balance = await fetchSteemBalance(username); if (balance !== null && steem) steem.textContent = balance; await renderLeaderboard(); return account; }
  function updateSessionSummary() { if (!summary) return; const accuracy = sessionQuestions ? Math.round((sessionCorrect / sessionQuestions) * 100) : 0; summary.textContent = `${t('gamesLabel')}: ${sessionQuestions ? 1 : 0} · ${t('accuracyLabel')}: ${accuracy}%`; } function setProgress(number) { const value = Math.max(0, Math.min(game.totalQuestions, Number(number) || 0)); if (progressBar) { progressBar.style.width = `${(value / game.totalQuestions) * 100}%`; progressBar.setAttribute('aria-valuenow', String(value)); } }
  function renderQuestion(question, points, number) { counter.textContent = `${t('question')} ${number} ${t('of')} ${game.totalQuestions}`; score.textContent = `${t('score')}: ${points}`; setProgress(number); flag.textContent = question.country[1]; answers.replaceChildren(); feedback.textContent = ''; feedback.className = 'feedback'; next.hidden = true; hideInfo(); question.options.forEach(([name]) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'answer'; button.textContent = name; button.onclick = () => chooseAnswer(button, name); answers.appendChild(button); }); }
  function chooseAnswer(button, name) { if (game.answered || game.completed || !username) return; const result = game.answer(name); if (!result) return; sessionQuestions++; if (result.correct) { sessionCorrect++; gameScore++; feedback.textContent = `${t('correct')} +1 D2E`; feedback.className = 'feedback ok'; button.classList.add('correct'); } else { gameScore--; feedback.textContent = `${t('wrong')} ${result.answer}`; feedback.className = 'feedback bad'; button.classList.add('wrong'); } for (const item of answers.children) { item.disabled = true; if (item.textContent === result.answer) item.classList.add('correct'); } score.textContent = `${t('score')}: ${gameScore}`; updateSessionSummary(); showInfo(result.answer); next.hidden = false; }
  function showHome() { loginView.hidden = true; home.hidden = false; leaderboard.hidden = false; gameView.hidden = true; hideInfo(); bindLogout(); setLogoutVisible(true); renderLeaderboard(); } function showGame() { loginView.hidden = true; home.hidden = true; leaderboard.hidden = true; gameView.hidden = false; hideInfo(); }
  async function newGame() { if (!username) return; newButton.disabled = true; try { account = await startGameOnServer(username); applyAccountToUI(); gameScore = 0; sessionQuestions = 0; sessionCorrect = 0; game.reset(); showGame(); game.next(); } catch (error) { console.error('Unable to start game', error); feedback.textContent = error?.message || 'Unable to start game.'; feedback.className = 'feedback bad'; await syncAccountFromD1(); } }
  async function restoreSession() { const savedUsername = readSession(); if (!savedUsername) return false; username = savedUsername; let lastError = null; for (let attempt = 1; attempt <= 3; attempt++) { try { await syncAccountFromD1(); loginFeedback.textContent = ''; showHome(); return true; } catch (error) { lastError = error; console.warn(`Persistent session restore attempt ${attempt} failed`, error); if (error?.message === 'ACCOUNT_NOT_FOUND') break; if (attempt < 3) await new Promise(resolve => setTimeout(resolve, 800 * attempt)); } } if (lastError?.message === 'ACCOUNT_NOT_FOUND') { clearSession(); username = null; account = null; loginFeedback.textContent = ''; loginView.hidden = false; home.hidden = true; leaderboard.hidden = true; gameView.hidden = true; setLogoutVisible(false); return false; } loginFeedback.textContent = 'Unable to restore your account. Please check your connection and refresh again.'; loginView.hidden = false; home.hidden = true; leaderboard.hidden = true; gameView.hidden = true; setLogoutVisible(false); return false; }
  loginForm.addEventListener('submit', async event => { event.preventDefault(); const enteredUsername = usernameInput.value.trim().toLowerCase(); const enteredPostingKey = key.value.trim(); if (!/^[a-z0-9.-]{3,32}$/.test(enteredUsername) || !enteredPostingKey) { loginFeedback.textContent = t('invalidPostingKey'); return; } loginFeedback.textContent = t('verifying'); try { await verifyPostingKey(enteredUsername, enteredPostingKey); username = enteredUsername; postingKey = enteredPostingKey; key.value = ''; await syncAccountFromD1(); writeSession(username); loginFeedback.textContent = ''; showHome(); } catch (error) { clearSession(); username = null; postingKey = null; console.error('Login failed', error); loginFeedback.textContent = error?.message || t('invalidPostingKey'); } });
  if (language) language.addEventListener('change', () => { setLanguage(language.value); applyLanguage(document, getLanguage()); if (!gameView.hidden && game.current) renderQuestion(game.current, game.score, game.questionNumber); }); newButton.onclick = newGame; if (resumeButton) { resumeButton.hidden = true; resumeButton.onclick = () => {}; }
  next.onclick = async () => { if (!game.isComplete()) { game.next(); return; } next.disabled = true; try { const eventId = `${username}-${Date.now()}-${crypto.randomUUID()}`; const result = await saveGameResult({ username, score: gameScore, eventId }); if (!result.success) throw new Error(result.error || 'Unable to save game result. Please try again.'); account = result.account; applyAccountToUI(); await renderLeaderboard(); next.disabled = false; showHome(); } catch (error) { console.error('Game result save failed', error); feedback.textContent = error?.message || 'Unable to save game result. Please try again.'; feedback.className = 'feedback bad'; next.disabled = false; } };
  window.addEventListener('steemflags:logout', () => { const button = getLogoutButton(); if (button) button.click(); }); window.addEventListener('steemflags:new-game', () => { if (username) newGame(); }); applyLanguage(document, getLanguage()); bindLogout(); setLogoutVisible(false); loginView.hidden = true; home.hidden = true; leaderboard.hidden = true; gameView.hidden = true; hideInfo(); restoreSession().then(restored => { if (!restored) loginView.hidden = false; });
}

bootstrap().catch(error => { console.error('Steem Flags startup failed', error); const loading = $('loading'); if (loading) loading.innerHTML = `<h2>Unable to load the game</h2><p>Startup error: ${String(error?.message || error)}</p><p>Please refresh the page.</p>`; });
