import './leaderboard.js';
import { FlagGame } from './game.js';
import { applyLanguage, getLanguage, t, setLanguage } from './i18n.js';
import { verifyPostingKey } from './steem-auth.js';
import { saveGameResult } from './reward.js';
import { loadMenu } from './menu.js';

const API_BASE='https://steemflags.mehdiq.workers.dev';
const SESSION_KEY='steemFlagsAuthSession';
const REWARD_STATE_KEY='steemFlagsPendingRewards';
const $=id=>document.getElementById(id);
async function loadComponent(){const r=await fetch('./components/app-shell.html?v=20260831-lbfix-01',{cache:'no-store'});if(!r.ok)throw Error(`Unable to load component: ${r.status}`);return r.text()}
async function loadAssetBar(){const m=$('assetBarMount');if(!m)return;const r=await fetch('./components/asset-bar.html?v=20260826-assetbar-03',{cache:'no-store'});if(!r.ok)throw Error(`Unable to load asset bar: ${r.status}`);m.innerHTML=await r.text()}
async function fetchAccount(u){const r=await fetch(`${API_BASE}/api/account?username=${encodeURIComponent(u)}`,{cache:'no-store'});if(!r.ok)throw Error(`ACCOUNT_API_${r.status}`);const d=await r.json();if(!d?.success||!d.account)throw Error('ACCOUNT_API_INVALID');return d.account}
async function fetchSteemBalance(a){const body=JSON.stringify({jsonrpc:'2.0',id:1,method:'condenser_api.get_accounts',params:[[a]]});for(const e of ['https://api.steemit.com','https://api.steem.house','https://api.steemyy.com'])try{const r=await fetch(e,{method:'POST',headers:{'Content-Type':'application/json'},body,cache:'no-store'}),d=await r.json(),b=d?.result?.[0]?.balance;if(typeof b==='string'&&/\d/.test(b))return b.replace(/\s*STEEM\s*$/i,'').trim()}catch{}return null}
function readSession(){try{const s=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');return s?.username||null}catch{return null}}function writeSession(u){localStorage.setItem(SESSION_KEY,JSON.stringify({username:u}))}function clearSession(){localStorage.removeItem(SESSION_KEY)}function savedKey(u){return u?`steemflagsGameState_${String(u).trim().toLowerCase()}`:null}function getSavedGame(u){try{const r=localStorage.getItem(savedKey(u));return r?JSON.parse(r):null}catch{return null}}function clearSavedGame(u){try{localStorage.removeItem(savedKey(u))}catch{}}function saveRewardState(s){try{localStorage.setItem(REWARD_STATE_KEY,JSON.stringify(s))}catch{}}function readRewardState(){try{const s=JSON.parse(localStorage.getItem(REWARD_STATE_KEY)||'null');return s?.username?s:null}catch{return null}}function clearRewardState(){try{localStorage.removeItem(REWARD_STATE_KEY)}catch{}}
function performLogout(){try{localStorage.removeItem(SESSION_KEY);localStorage.removeItem(REWARD_STATE_KEY);sessionStorage.removeItem('steemFlagsSponsorContext');sessionStorage.removeItem('steemFlagsSponsorReward')}catch{}window.location.replace('./index.html')}
async function bootstrap(){const a=$('app');a.innerHTML=await loadComponent();await loadAssetBar();await loadMenu();await start()}
async function start(){const query=new URLSearchParams(location.search);if(query.get('logout')==='1'){performLogout();return}let username=null,account=null,gameScore=0,sessionCorrect=0;const loginView=$('loginView'),home=$('homeView'),leaderboard=$('leaderboardSection'),gameView=$('gameView'),answers=$('answers'),feedback=$('feedback'),next=$('nextButton'),energy=$('energyValue'),d2e=$('sfValue'),steem=$('steemValue'),assets=$('assetStats'),counter=$('questionCounter'),score=$('scoreLabel'),flag=$('flagImage'),newButton=$('newGameButton'),resumeButton=$('resumeGameButton'),summary=$('progressSummary'),loginForm=$('loginForm'),usernameInput=$('usernameInput'),loginFeedback=$('loginFeedback'),loggedIn=$('loggedInUser'),language=$('languageSelect'),progressBar=$('quizProgressBar'),info=$('countryInfoLink'),key=$('postingKeyInput');const game=new FlagGame(renderQuestion);window.__steemFlagsStartNewGame=()=>newGame();
function applyAccount(){if(!account)return;energy.textContent=Number(account.Energy)||0;d2e.textContent=Number(account.D2E)||0;newButton.disabled=Number(account.Energy)<=0}function updateResume(){const saved=getSavedGame(username);if(resumeButton){resumeButton.hidden=!saved?.current||!!saved?.completed;resumeButton.disabled=!saved?.current||!!saved?.completed}if(summary)summary.hidden=false}async function sync(){account=await fetchAccount(username);applyAccount();updateResume();if(assets)assets.hidden=false;if(loggedIn)loggedIn.textContent=`${t('loggedInAs')} @${username}`;const b=await fetchSteemBalance(username);if(b!==null)steem.textContent=String(Math.floor(Number.parseFloat(b)||0))}function hideMoreInformation(){if(!info)return;info.hidden=true;info.style.display='none';info.setAttribute('aria-hidden','true');info.tabIndex=-1;info.removeAttribute('href')}
function renderQuestion(q,p,n){counter.textContent=`${t('question')} ${n} ${t('of')} ${game.totalQuestions}`;score.textContent=`${t('score')}: ${p}`;progressBar.style.width=`${n/game.totalQuestions*100}%`;flag.textContent=q.country[1];answers.replaceChildren();feedback.textContent='';feedback.className='feedback';next.hidden=true;hideMoreInformation();q.options.forEach(([name])=>{const b=document.createElement('button');b.type='button';b.className='answer';b.dataset.canonical=name;b.textContent=name;b.onclick=()=>choose(b);answers.appendChild(b)})}
function showMoreInformation(){if(!info||!game.current?.country)return;const countryName=game.current.country[0];info.href=`https://en.wikipedia.org/wiki/${encodeURIComponent(countryName.replace(/\s+/g,'_'))}`;info.hidden=false;info.style.display='block';info.removeAttribute('aria-hidden');info.removeAttribute('tabindex');info.textContent=t('moreInfo')}
function choose(btn){const canonical=btn?.dataset?.canonical;if(!canonical)return;const r=game.answer(canonical);if(!r)return;if(r.correct){sessionCorrect++;gameScore++;feedback.textContent='✅ Correct Answer: +1 D2E';btn.classList.add('correct')}else{gameScore--;feedback.textContent=`❌ Wrong Answer: -1 D2E\n${r.answer}`;btn.classList.add('wrong')}for(const b of answers.children){b.disabled=true;if(b.dataset.canonical===r.answer)b.classList.add('correct')}score.textContent=`${t('score')}: ${gameScore}`;showMoreInformation();next.hidden=false;if(r.complete)clearSavedGame(username)}
function showHome(){loginView.hidden=true;home.hidden=false;leaderboard.hidden=false;gameView.hidden=true;updateResume();window.dispatchEvent(new CustomEvent('steemflags:show-home'))}function showGame(){loginView.hidden=true;home.hidden=true;leaderboard.hidden=true;gameView.hidden=false}
async function newGame(){if(!username){feedback.textContent=t('loginPrompt');return}if(newButton.dataset.busy==='1')return;newButton.dataset.busy='1';newButton.disabled=true;newButton.setAttribute('aria-busy','true');feedback.textContent='';feedback.className='feedback';const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch(`${API_BASE}/api/game/start`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username}),cache:'no-store',signal:controller.signal});const text=await r.text();let d=null;try{d=JSON.parse(text)}catch{}if(!r.ok||!d?.success)throw Error(d?.error||`Unable to start game (${r.status})`);if(!d.account)throw Error('Game started but account data was not returned');account=d.account;gameScore=0;sessionCorrect=0;clearSavedGame(username);game.reset();applyAccount();showGame();game.next()}catch(e){feedback.textContent=e?.name==='AbortError'?'Game server did not respond. Please try again.':(e?.message||'Unable to start game.');feedback.className='feedback bad';try{account=await fetchAccount(username);applyAccount()}catch{}}finally{clearTimeout(timer);newButton.dataset.busy='0';newButton.removeAttribute('aria-busy');newButton.disabled=Number(account?.Energy)<=0}}
async function resumeGame(){const saved=getSavedGame(username);if(!saved?.current){updateResume();return}if(!game.restore(saved)){clearSavedGame(username);updateResume();return}gameScore=Number(saved.score)||0;sessionCorrect=0;showGame();if(game.answered)game.next();else renderQuestion(game.current,game.score,game.questionNumber)}
resumeButton.onclick=resumeGame;newButton.onclick=e=>{e.preventDefault();e.stopPropagation();newGame()};window.addEventListener('steemflags:new-game',()=>newGame());window.addEventListener('steemflags:resume-game',()=>resumeGame());
loginForm.addEventListener('submit',async e=>{e.preventDefault();const u=usernameInput.value.trim().toLowerCase(),k=key.value.trim();loginFeedback.textContent=t('verifying');try{await verifyPostingKey(u,k);username=u;key.value='';writeSession(u);await sync();showHome()}catch(err){clearSession();username=null;loginFeedback.textContent=err.message||t('invalidPostingKey')}});
next.onclick=async()=>{if(!game.isComplete()){game.next();return}next.disabled=true;try{const perfect=sessionCorrect===game.totalQuestions;const result=await saveGameResult({username,score:gameScore,perfect,eventId:`${username}-${Date.now()}-${crypto.randomUUID()}`});if(!result.success)throw Error(result.error||'Unable to save game result.');account=result.account;applyAccount();clearSavedGame(username);saveRewardState({username,gameReward:Number(result.score)||gameScore,perfectBonus:Number(result.perfectBonus)||0,adReward:0,context:'game'});showHome()}catch(e){feedback.textContent=e.message||'Unable to save game result.';feedback.className='feedback bad'}finally{next.disabled=false}};
if(language){language.onchange=()=>{const lang=setLanguage(language.value);applyLanguage(document,lang);if(!gameView.hidden&&game.current)renderQuestion(game.current,game.score,game.questionNumber)}}
applyLanguage(document,getLanguage());loginView.hidden=true;home.hidden=true;leaderboard.hidden=true;gameView.hidden=true;username=readSession();if(username){try{await sync();showHome()}catch{clearSession();username=null;loginView.hidden=false}}else loginView.hidden=false}
bootstrap().then(()=>window.dispatchEvent(new CustomEvent('steemflags:ready',{detail:{success:true}}))).catch(console.error);
