import { loadState, saveState, resetState, refreshDailyEnergy, getStoredUsername, setStoredUsername, clearStoredUsername } from './storage.js';
import { FlagGame } from './game.js';
import { loadProgress, recordAnswer, recordGame, saveProgress, accuracy } from './progression.js';
import { applyLanguage, getLanguage, t, setLanguage } from './i18n.js';
import { verifyPostingKey } from './steem-auth.js';
const COMPONENTS = { appShell: './components/app-shell.html' }; const $ = (id) => document.getElementById(id);
const GAME_STATE_PREFIX = 'steemflags.incompleteGame.v1_'; const gameStateKey = (username) => `${GAME_STATE_PREFIX}${encodeURIComponent(String(username).trim().toLowerCase())}`;
function loadIncompleteGame(username) { if (!username) return null; try { return JSON.parse(localStorage.getItem(gameStateKey(username)) || 'null'); } catch { return null; } }
function saveIncompleteGame(username, game) { if (username && game.hasProgress()) localStorage.setItem(gameStateKey(username), JSON.stringify(game.serialize())); }
function clearIncompleteGame(username) { if (username) localStorage.removeItem(gameStateKey(username)); }
async function loadComponent(path) { const response = await fetch(`${path}?v=20260817-14`, { cache: 'no-store' }); if (!response.ok) throw new Error(`Unable to load component: ${response.status}`); return response.text(); }
async function loadLeaderboardModule() { try { await import(`./leaderboard.js?v=${Date.now()}`); } catch (error) { console.warn('Leaderboard module failed to load:', error); } }
async function fetchSteemBalance(account) { const endpoints = ['https://api.steemit.com', 'https://api.steem.house']; for (const endpoint of endpoints) { try { const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'condenser_api.get_accounts', params: [[account]] }) }); if (!response.ok) continue; const payload = await response.json(); const balance = payload?.result?.[0]?.balance; if (typeof balance === 'string') return balance.replace(/\s*STEEM\s*$/i, '').trim(); } catch (error) { console.warn('Steem balance lookup failed:', endpoint, error); } } return '—'; }
async function bootstrap() { const app = $('app'); try { app.innerHTML = await loadComponent(COMPONENTS.appShell); await loadLeaderboardModule(); startApplication(); } catch (error) { console.error('Steem Flags bootstrap failed:', error); app.innerHTML = '<main class="appShell"><section class="card"><h1>Steem Flags</h1><p class="muted">The game interface could not be loaded. Please refresh the page.</p></section></main>'; } }
function startApplication() {
  let username = getStoredUsername(); let state = loadState(username); let progress = loadProgress(username);
  const loginView = $('loginView'), home = $('homeView'), leaderboardSection = $('leaderboardSection'), gameView = $('gameView'), answers = $('answers'); const feedback = $('feedback'), next = $('nextButton'), energy = $('energyValue'), sf = $('sfValue'), steem = $('steemValue'), assetStats = $('assetStats'); const counter = $('questionCounter'), score = $('scoreLabel'), flag = $('flagImage'); const newGameButton = $('newGameButton'), resumeGameButton = $('resumeGameButton'), progressSummary = $('progressSummary'), menu = $('menu'), menuButton = $('menuButton'); const loginForm = $('loginForm'), usernameInput = $('usernameInput'), loginFeedback = $('loginFeedback'); const loggedInUser = $('loggedInUser'), logout = document.querySelector('[data-action="logout"]'); const languageSelect = $('languageSelect'); const quizProgressBar = $('quizProgressBar'), countryInfoLink = $('countryInfoLink');
  let postingKeyInput = $('postingKeyInput'); if (!postingKeyInput) { const label = document.createElement('label'); label.htmlFor = 'postingKeyInput'; label.dataset.i18n = 'postingKeyLabel'; const input = document.createElement('input'); input.id = 'postingKeyInput'; input.name = 'postingKey'; input.type = 'password'; input.autocomplete = 'off'; input.required = true; label.textContent = 'Posting Key'; loginForm.insertBefore(label, $('loginButton')); loginForm.insertBefore(input, $('loginButton')); postingKeyInput = input; }
  const game = new FlagGame(renderQuestion); let answered = false;
  function hideCountryInfo() { countryInfoLink.hidden = true; countryInfoLink.removeAttribute('href'); countryInfoLink.setAttribute('aria-hidden', 'true'); countryInfoLink.tabIndex = -1; countryInfoLink.style.setProperty('display', 'none', 'important'); }
  function showCountryInfo() { countryInfoLink.hidden = false; countryInfoLink.setAttribute('aria-hidden', 'false'); countryInfoLink.tabIndex = 0; countryInfoLink.style.setProperty('display', 'block', 'important'); }
  function applyCurrentLanguage() { const language = getLanguage(); applyLanguage(document, language); languageSelect.value = language; renderStats(); }
  function renderStats() { energy.textContent = state.energy; sf.textContent = state.sf; newGameButton.disabled = !username || state.energy <= 0; progressSummary.hidden = !username; assetStats.hidden = !username; const incomplete = username ? loadIncompleteGame(username) : null; resumeGameButton.hidden = !Boolean(incomplete); if (username) progressSummary.textContent = `${t('gamesLabel')}: ${progress.games} · ${t('accuracyLabel')}: ${accuracy(progress)}%`; loggedInUser.textContent = username ? `${t('loggedInAs')} @${username}` : ''; }
  async function refreshSteemBalance() { if (!username) return; steem.textContent = '…'; steem.textContent = await fetchSteemBalance(username); }
  async function syncGlobalSF() { if (username && typeof window.submitGlobalSF === 'function') await window.submitGlobalSF(username, state.sf); }
  function updateQuizProgress(number) { const value = Math.max(0, Math.min(game.totalQuestions, Number(number) || 0)); quizProgressBar.style.width = `${(value / game.totalQuestions) * 100}%`; quizProgressBar.setAttribute('aria-valuenow', String(value)); }
  function wikipediaLanguageCode() { const language = getLanguage(); return language === 'fa' ? 'fa' : language === 'es' ? 'es' : 'en'; }
  async function wikipediaUrl(countryName) { const code = wikipediaLanguageCode(); const sourceTitle = String(countryName).trim().replace(/ /g, '_'); if (code === 'en') return `https://en.wikipedia.org/wiki/${encodeURIComponent(sourceTitle)}`; try { const endpoint = `https://en.wikipedia.org/w/api.php?action=query&prop=langlinks&lllang=${encodeURIComponent(code)}&lllimit=1&format=json&origin=*&titles=${encodeURIComponent(sourceTitle)}`; const response = await fetch(endpoint, { cache: 'no-store' }); if (response.ok) { const data = await response.json(); const pages = Object.values(data?.query?.pages || {}); const translated = pages[0]?.langlinks?.[0]?.['*']; if (translated) return `https://${code}.wikipedia.org/wiki/${encodeURIComponent(translated.replace(/ /g, '_'))}`; } } catch (error) { console.warn('Wikipedia language-link lookup failed:', error); } return `https://${code}.wikipedia.org/w/index.php?search=${encodeURIComponent(countryName)}`; }
  async function revealCountryInfo(countryName) { hideCountryInfo(); countryInfoLink.textContent = 'ℹ️ More information about this country'; const url = await wikipediaUrl(countryName); countryInfoLink.href = url; showCountryInfo(); }
  function showLoggedOut() { loginView.hidden = false; home.hidden = true; leaderboardSection.hidden = true; gameView.hidden = true; logout.hidden = true; menu.hidden = true; assetStats.hidden = true; steem.textContent = '—'; menuButton.setAttribute('aria-expanded', 'false'); usernameInput.value = ''; postingKeyInput.value = ''; loginFeedback.textContent = ''; hideCountryInfo(); renderStats(); }
  function showHome() { loginView.hidden = true; home.hidden = false; leaderboardSection.hidden = false; gameView.hidden = true; hideCountryInfo(); renderStats(); }
  function showLoggedIn() { showHome(); logout.hidden = false; state = refreshDailyEnergy(loadState(username), username); progress = loadProgress(username); renderStats(); refreshSteemBalance(); syncGlobalSF(); }
  function showGame() { loginView.hidden = true; home.hidden = true; leaderboardSection.hidden = true; gameView.hidden = false; hideCountryInfo(); }
  function renderQuestion(question, points, number) { answered = false; counter.textContent = `${t('question')} ${number} ${t('of')} ${game.totalQuestions}`; score.textContent = `${t('score')}: ${points}`; updateQuizProgress(number); flag.textContent = question.country[1]; flag.setAttribute('aria-label', `${question.country[0]} flag`); answers.replaceChildren(); feedback.textContent = ''; feedback.className = 'feedback'; hideCountryInfo(); next.hidden = true; question.options.forEach(([name]) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'answer'; button.textContent = name; button.addEventListener('click', () => choose(button, name), { once: true }); answers.appendChild(button); }); }
  async function restoreQuestion() { if (!game.current) return; answered = game.answered; counter.textContent = `${t('question')} ${game.questionNumber} ${t('of')} ${game.totalQuestions}`; score.textContent = `${t('score')}: ${game.score}`; updateQuizProgress(game.questionNumber); flag.textContent = game.current.country[1]; flag.setAttribute('aria-label', `${game.current.country[0]} flag`); answers.replaceChildren(); game.current.options.forEach(([name]) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'answer'; button.textContent = name; button.disabled = game.answered; if (game.answered && name === game.current.country[0]) button.classList.add('correct'); button.addEventListener('click', () => choose(button, name), { once: true }); answers.appendChild(button); }); if (game.answered) { feedback.textContent = game.score >= 0 ? `${t('correct')} / ${t('score')}: ${game.score}` : `${t('wrong')} / ${t('score')}: ${game.score}`; feedback.className = 'feedback'; await revealCountryInfo(game.current.country[0]); next.hidden = false; } else { feedback.textContent = ''; hideCountryInfo(); next.hidden = true; } }
  async function choose(button, name) { if (answered || !username) return; const result = game.answer(name); if (!result) return; answered = true; progress = recordAnswer(progress, result.correct); if (result.correct) { state.sf += 1; feedback.textContent = `${t('correct')} +1 SF`; feedback.className = 'feedback ok'; button.classList.add('correct'); } else { state.sf -= 1; feedback.textContent = `${t('wrong')} ${result.answer}`; feedback.className = 'feedback bad'; button.classList.add('wrong'); } [...answers.children].forEach((answerButton) => { answerButton.disabled = true; if (answerButton.textContent === result.answer) answerButton.classList.add('correct'); }); hideCountryInfo(); saveState(state, username); saveProgress(progress, username); saveIncompleteGame(username, game); renderStats(); syncGlobalSF(); next.hidden = false; await revealCountryInfo(result.answer); }
  function newGame() { if (!username) return showLoggedOut(); state = refreshDailyEnergy(loadState(username), username); renderStats(); if (state.energy <= 0) return; clearIncompleteGame(username); state.energy -= 1; saveState(state, username); game.reset(); progress = recordGame(progress); saveProgress(progress, username); renderStats(); showGame(); game.next(); saveIncompleteGame(username, game); }
  function resumeGame() { if (!username) return; const snapshot = loadIncompleteGame(username); if (!snapshot || !game.restore(snapshot)) { clearIncompleteGame(username); renderStats(); return; } showGame(); restoreQuestion(); }
  loginForm.addEventListener('submit', async (event) => { event.preventDefault(); const value = usernameInput.value.trim().toLowerCase(); const postingKey = postingKeyInput.value.trim(); if (!/^[a-z0-9.-]{3,32}$/.test(value)) { loginFeedback.textContent = t('invalidUsername'); loginFeedback.className = 'feedback bad'; return; } if (!postingKey) { loginFeedback.textContent = t('invalidPostingKey'); loginFeedback.className = 'feedback bad'; return; } const loginButton = $('loginButton'); loginButton.disabled = true; loginFeedback.textContent = t('verifying'); loginFeedback.className = 'feedback'; try { await verifyPostingKey(value, postingKey); username = setStoredUsername(value); postingKeyInput.value = ''; loginFeedback.textContent = ''; showLoggedIn(); } catch (error) { console.error('Steem login verification failed:', error); username = null; const messages = { AUTH_LIBRARY_UNAVAILABLE: 'Authentication library could not be loaded. Refresh and try again.', POSTING_KEY_EMPTY: t('invalidPostingKey'), POSTING_KEY_FORMAT: 'The Posting Key format is invalid. Use the private Posting Key beginning with 5.', ACCOUNT_NOT_FOUND: 'Steem account not found.', POSTING_KEY_UNAUTHORIZED: 'This Posting Key is not authorized for the posting authority of this account.', STEEM_RPC_UNAVAILABLE: 'Steem network could not be reached. Please try again.' }; loginFeedback.textContent = messages[error?.message] || t('invalidPostingKey'); loginFeedback.className = 'feedback bad'; } finally { loginButton.disabled = false; } });
  logout.addEventListener('click', () => { clearStoredUsername(); username = null; state = loadState(); progress = loadProgress(); game.reset(); showLoggedOut(); });
  languageSelect.addEventListener('change', () => { setLanguage(languageSelect.value); applyCurrentLanguage(); if (!gameView.hidden && game.current) restoreQuestion(); });
  newGameButton.addEventListener('click', newGame); resumeGameButton.addEventListener('click', resumeGame); next.addEventListener('click', () => { if (game.isComplete()) { clearIncompleteGame(username); showHome(); feedback.textContent = t('gameComplete'); renderStats(); syncGlobalSF(); return; } game.next(); saveIncompleteGame(username, game); });
  menuButton.addEventListener('click', (event) => { event.preventDefault(); event.stopPropagation(); menu.hidden = !menu.hidden; menuButton.setAttribute('aria-expanded', String(!menu.hidden)); });
  document.querySelectorAll('[data-action="home"]').forEach((button) => button.addEventListener('click', () => { showHome(); menu.hidden = true; menuButton.setAttribute('aria-expanded', 'false'); renderStats(); }));
  document.querySelectorAll('[data-action="reset"]').forEach((button) => button.addEventListener('click', () => { if (!username) return; clearIncompleteGame(username); state = refreshDailyEnergy(resetState(username), username); game.reset(); progress = loadProgress(username); renderStats(); showHome(); menu.hidden = true; menuButton.setAttribute('aria-expanded', 'false'); refreshSteemBalance(); syncGlobalSF(); }));
  applyCurrentLanguage(); if (username) showLoggedIn(); else showLoggedOut();
}
bootstrap();