import { loadState, saveState, resetState, refreshDailyEnergy, getStoredUsername, setStoredUsername, clearStoredUsername } from './storage.js';
import { FlagGame } from './game.js';
import { loadProgress, recordAnswer, recordGame, saveProgress, accuracy } from './progression.js';
import { applyLanguage, getLanguage, t, setLanguage } from './i18n.js';
import { verifyPostingKey } from './steem-auth.js';
const COMPONENTS = { appShell: './components/app-shell.html' }; const $ = (id) => document.getElementById(id);
async function loadComponent(path) { const response = await fetch(`${path}?v=20260817-3`, { cache: 'no-store' }); if (!response.ok) throw new Error(`Unable to load component: ${response.status}`); return response.text(); }
async function fetchSteemBalance(account) { const endpoints = ['https://api.steemit.com', 'https://api.steem.house']; for (const endpoint of endpoints) { try { const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'condenser_api.get_accounts', params: [[account]] }) }); if (!response.ok) continue; const payload = await response.json(); const balance = payload?.result?.[0]?.balance; if (typeof balance === 'string') return balance.replace(/\s*STEEM\s*$/i, '').trim(); } catch (error) { console.warn('Steem balance lookup failed:', endpoint, error); } } return '—'; }
async function bootstrap() { const app = $('app'); try { app.innerHTML = await loadComponent(COMPONENTS.appShell); startApplication(); } catch (error) { console.error('Steem Flags bootstrap failed:', error); app.innerHTML = '<main class="appShell"><section class="card"><h1>Steem Flags</h1><p class="muted">The game interface could not be loaded. Please refresh the page.</p></section></main>'; } }
function startApplication() {
  let username = getStoredUsername(); let state = loadState(username); let progress = loadProgress(username);
  const loginView = $('loginView'), home = $('homeView'), leaderboardSection = $('leaderboardSection'), gameView = $('gameView'), answers = $('answers'); const feedback = $('feedback'), next = $('nextButton'), energy = $('energyValue'), sf = $('sfValue'), steem = $('steemValue'), assetStats = $('assetStats'); const counter = $('questionCounter'), score = $('scoreLabel'), flag = $('flagImage'); const start = $('startButton'), progressSummary = $('progressSummary'), menu = $('menu'), menuButton = $('menuButton'); const loginForm = $('loginForm'), usernameInput = $('usernameInput'), loginFeedback = $('loginFeedback'); const loggedInUser = $('loggedInUser'), logout = document.querySelector('[data-action="logout"]'); const languageSelect = $('languageSelect');
  let postingKeyInput = $('postingKeyInput');
  if (!postingKeyInput) { const label = document.createElement('label'); label.htmlFor = 'postingKeyInput'; label.dataset.i18n = 'postingKeyLabel'; const input = document.createElement('input'); input.id = 'postingKeyInput'; input.name = 'postingKey'; input.type = 'password'; input.autocomplete = 'off'; input.required = true; label.textContent = 'Posting Key'; loginForm.insertBefore(label, $('loginButton')); loginForm.insertBefore(input, $('loginButton')); postingKeyInput = input; }
  const game = new FlagGame(renderQuestion); let answered = false;
  function applyCurrentLanguage() { const language = getLanguage(); applyLanguage(document, language); languageSelect.value = language; renderStats(); }
  function renderStats() { energy.textContent = state.energy; sf.textContent = state.sf; start.disabled = !username || state.energy <= 0; start.textContent = state.energy > 0 ? t('startGame') : t('noEnergy'); progressSummary.hidden = !username; assetStats.hidden = !username; if (username) progressSummary.textContent = `${t('gamesLabel')}: ${progress.games} · ${t('accuracyLabel')}: ${accuracy(progress)}%`; loggedInUser.textContent = username ? `${t('loggedInAs')} @${username}` : ''; }
  async function refreshSteemBalance() { if (!username) return; steem.textContent = '…'; steem.textContent = await fetchSteemBalance(username); }
  async function syncGlobalSF() { if (username && typeof window.submitGlobalSF === 'function') await window.submitGlobalSF(username, state.sf); }
  function showLoggedOut() { loginView.hidden = false; home.hidden = true; leaderboardSection.hidden = true; gameView.hidden = true; logout.hidden = true; menu.hidden = true; assetStats.hidden = true; steem.textContent = '—'; menuButton.setAttribute('aria-expanded', 'false'); usernameInput.value = ''; postingKeyInput.value = ''; loginFeedback.textContent = ''; renderStats(); }
  function showHome() { loginView.hidden = true; home.hidden = false; leaderboardSection.hidden = false; gameView.hidden = true; }
  function showLoggedIn() { showHome(); logout.hidden = false; state = refreshDailyEnergy(loadState(username), username); progress = loadProgress(username); renderStats(); refreshSteemBalance(); syncGlobalSF(); }
  function showGame() { home.hidden = true; leaderboardSection.hidden = true; gameView.hidden = false; }
  function renderQuestion(question, points, number) { answered = false; counter.textContent = `${t('question')} ${number} ${t('of')} ${game.totalQuestions}`; score.textContent = `${t('score')}: ${points}`; flag.textContent = question.country[1]; flag.setAttribute('aria-label', `${question.country[0]} flag`); answers.replaceChildren(); feedback.textContent = ''; feedback.className = 'feedback'; next.hidden = true; question.options.forEach(([name]) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'answer'; button.textContent = name; button.addEventListener('click', () => choose(button, name), { once: true }); answers.appendChild(button); }); }
  function choose(button, name) { if (answered || !username) return; const result = game.answer(name); if (!result) return; answered = true; progress = recordAnswer(progress, result.correct); if (result.correct) { state.sf += 1; feedback.textContent = `${t('correct')} +1 SF`; feedback.className = 'feedback ok'; button.classList.add('correct'); } else { state.sf -= 1; feedback.textContent = `${t('wrong')} ${result.answer}`; feedback.className = 'feedback bad'; button.classList.add('wrong'); } [...answers.children].forEach((answerButton) => { answerButton.disabled = true; if (answerButton.textContent === result.answer) answerButton.classList.add('correct'); }); saveState(state, username); saveProgress(progress, username); renderStats(); syncGlobalSF(); next.hidden = false; }
  function startGame() { if (!username) return showLoggedOut(); state = refreshDailyEnergy(loadState(username), username); renderStats(); if (state.energy <= 0) return; state.energy -= 1; saveState(state, username); game.reset(); progress = recordGame(progress); saveProgress(progress, username); renderStats(); showGame(); game.next(); }
  loginForm.addEventListener('submit', async (event) => { event.preventDefault(); const value = usernameInput.value.trim().toLowerCase(); const postingKey = postingKeyInput.value.trim(); if (!/^[a-z0-9.-]{3,32}$/.test(value)) { loginFeedback.textContent = t('invalidUsername'); loginFeedback.className = 'feedback bad'; return; } if (!postingKey) { loginFeedback.textContent = t('invalidPostingKey'); loginFeedback.className = 'feedback bad'; return; } const loginButton = $('loginButton'); loginButton.disabled = true; loginFeedback.textContent = t('verifying'); loginFeedback.className = 'feedback'; try { await verifyPostingKey(value, postingKey); username = setStoredUsername(value); postingKeyInput.value = ''; loginFeedback.textContent = ''; showLoggedIn(); } catch (error) { console.error('Steem login verification failed:', error); username = null; const messages = { AUTH_LIBRARY_UNAVAILABLE: 'Authentication library could not be loaded. Refresh and try again.', POSTING_KEY_EMPTY: t('invalidPostingKey'), POSTING_KEY_FORMAT: 'The Posting Key format is invalid. Use the private Posting Key beginning with 5.', ACCOUNT_NOT_FOUND: 'Steem account not found.', POSTING_KEY_UNAUTHORIZED: 'This Posting Key is not authorized for the posting authority of this account.', STEEM_RPC_UNAVAILABLE: 'Steem network could not be reached. Please try again.' }; loginFeedback.textContent = messages[error?.message] || t('invalidPostingKey'); loginFeedback.className = 'feedback bad'; } finally { loginButton.disabled = false; } });
  logout.addEventListener('click', () => { clearStoredUsername(); username = null; state = loadState(); progress = loadProgress(); game.reset(); showLoggedOut(); });
  languageSelect.addEventListener('change', () => { setLanguage(languageSelect.value); applyCurrentLanguage(); if (!gameView.hidden && game.current) renderQuestion(game.current, game.score, game.questionNumber); });
  start.addEventListener('click', startGame); next.addEventListener('click', () => { if (game.isComplete()) { showHome(); feedback.textContent = t('gameComplete'); renderStats(); syncGlobalSF(); return; } game.next(); });
  menuButton.addEventListener('click', (event) => { event.preventDefault(); event.stopPropagation(); menu.hidden = !menu.hidden; menuButton.setAttribute('aria-expanded', String(!menu.hidden)); });
  document.querySelectorAll('[data-action="home"]').forEach((button) => button.addEventListener('click', () => { showHome(); menu.hidden = true; menuButton.setAttribute('aria-expanded', 'false'); renderStats(); }));
  document.querySelectorAll('[data-action="reset"]').forEach((button) => button.addEventListener('click', () => { if (!username) return; state = refreshDailyEnergy(resetState(username), username); game.reset(); progress = loadProgress(username); renderStats(); showHome(); menu.hidden = true; menuButton.setAttribute('aria-expanded', 'false'); refreshSteemBalance(); syncGlobalSF(); }));
  applyCurrentLanguage(); if (username) showLoggedIn(); else showLoggedOut();
}
bootstrap();