const API_BASE='https://steemflags.mehdiq.workers.dev';
const REWARD_POOL_URL='./steemrewardpool.html?v=20260828-rewardpool-06';
const status=document.getElementById('leaderboardStatus');
const body=document.getElementById('leaderboardBody');
const pool=document.getElementById('rewardPool');
function avatarUrl(username){return `https://steemitimages.com/u/${encodeURIComponent(username)}/avatar`;}
function escapeHtml(value){return String(value).replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
async function loadRewardPool(){if(!pool)return;try{const response=await fetch(REWARD_POOL_URL,{cache:'no-store'});if(!response.ok)throw new Error(`REWARD_POOL_${response.status}`);const html=await response.text();const doc=new DOMParser().parseFromString(html,'text/html');const source=doc.querySelector('.reward-card');if(!source)throw new Error('REWARD_POOL_MARKUP_MISSING');const title=source.querySelector('h1')?.textContent?.trim()||'💰 Weekly $STEEM Rewards Pool';const items=[...source.querySelectorAll('.item')].map(el=>el.textContent.trim());pool.innerHTML=`<div style="width:100%;margin:10px 0 16px;padding:14px 16px;border:1px solid rgba(255,255,255,.18);border-radius:14px;background:linear-gradient(145deg,#111c31,#0b1324);box-sizing:border-box;text-align:left"><div style="margin:0 0 10px;font-family:Arial,Helvetica,sans-serif;font-size:18px;line-height:1.3;font-weight:700;white-space:normal">${escapeHtml(title)}</div>${items.map(item=>`<div style="margin:7px 0;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.45;font-weight:500;white-space:normal">${escapeHtml(item)}</div>`).join('')}</div>`;}catch(error){console.error('Reward pool load failed:',error);pool.innerHTML='<div style="width:100%;margin:10px 0 16px;padding:14px 16px;border:1px solid rgba(255,255,255,.18);border-radius:14px;box-sizing:border-box"><div style="font-size:18px;font-weight:700">💰 Weekly $STEEM Rewards Pool</div><div style="font-size:14px;margin-top:8px">Unable to load reward pool.</div></div>';}}
function render(accounts){if(!body)return;const rows=accounts.map((account,index)=>{const username=String(account?.Username||account?.username||'—');const d2e=Math.max(0,Number(account?.D2E??account?.d2e)||0);const medal=index===0?'🥇':index===1?'🥈':index===2?'🥉':String(index+1);const avatar=avatarUrl(username);return `<tr><td>${medal}</td><td><div class="leaderboardUser"><img class="leaderboardAvatar" src="${avatar}" alt="@${escapeHtml(username)}" loading="lazy" onerror="this.style.visibility='hidden'"><span>@${escapeHtml(username)}</span></div></td><td>${d2e.toLocaleString()} D2E</td></tr>`;}).join('');body.innerHTML=rows||'<tr><td colspan="3" class="muted">No players yet.</td></tr>';if(status)status.hidden=true;}
async function loadLeaderboard(){if(!status||!body)return;status.hidden=false;status.textContent='Loading leaderboard…';await loadRewardPool();try{const response=await fetch(`${API_BASE}/api/accounts?limit=100`,{cache:'no-store'});if(!response.ok)throw new Error(`LEADERBOARD_API_${response.status}`);const data=await response.json();if(!data?.success||!Array.isArray(data.accounts))throw new Error('LEADERBOARD_API_INVALID');const accounts=data.accounts.slice().sort((a,b)=>{const ad=Number(a?.D2E)||0,bd=Number(b?.D2E)||0;return bd-ad||String(a?.Username||'').localeCompare(String(b?.Username||''));});render(accounts);}catch(error){console.error('Leaderboard load failed:',error);status.hidden=false;status.textContent='Unable to load leaderboard. Please refresh the page.';body.innerHTML='';}}
loadLeaderboard();
