import { applyLanguage, getLanguage, setLanguage } from './i18n.js';
export async function loadMenu(){
 const container=document.getElementById("menuContainer");if(!container)return;
 const response=await fetch("./components/menu.html?v=20260903-i18n-all-01",{cache:"no-store"});if(!response.ok)throw new Error(`Unable to load menu: ${response.status}`);container.innerHTML=await response.text();
 const menuButton=document.getElementById("menuButton"),menu=document.getElementById("menu");if(!menuButton||!menu)return;
 const logoutLink=menu.querySelector('[data-action="logout"]');
 if(logoutLink){let loggedIn=false;try{const session=JSON.parse(localStorage.getItem("steemFlagsAuthSession")||"null");const legacy=localStorage.getItem("steemflags.username");loggedIn=!!(session?.username||legacy)}catch{}logoutLink.hidden=!loggedIn}
 function positionElements(){const rtl=document.documentElement.dir==="rtl",edge="max(12px, 4vw)";menuButton.style.setProperty("position","absolute","important");menuButton.style.setProperty("left",rtl?"auto":edge,"important");menuButton.style.setProperty("right",rtl?edge:"auto","important");menuButton.style.setProperty("top","50%","important");menuButton.style.setProperty("transform","translateY(-50%)","important");menuButton.style.setProperty("z-index","110","important");menu.style.setProperty("position","fixed","important");menu.style.setProperty("left",rtl?"auto":edge,"important");menu.style.setProperty("right",rtl?edge:"auto","important")}
 positionElements();applyLanguage(menu,getLanguage());
 const languageSelect=document.getElementById('languageSelect');
 if(languageSelect){languageSelect.value=getLanguage();languageSelect.addEventListener('change',()=>{const lang=setLanguage(languageSelect.value);applyLanguage(document,lang);applyLanguage(menu,lang);positionElements();if(location.pathname.endsWith('/index.html')||location.pathname.endsWith('/'))return;location.reload()})}
 function closeMenu(){menu.hidden=true;menuButton.setAttribute("aria-expanded","false")}
 menuButton.onclick=e=>{e.stopPropagation();menu.hidden=!menu.hidden;menuButton.setAttribute("aria-expanded",String(!menu.hidden));if(!menu.hidden)positionElements()};
 menu.addEventListener("click",event=>{const link=event.target.closest("[data-action]");if(!link)return;const action=link.dataset.action;if(action==="new-game"){event.preventDefault();window.dispatchEvent(new CustomEvent("steemflags:new-game"));closeMenu();return}if(action==="resume-game"){event.preventDefault();window.dispatchEvent(new CustomEvent("steemflags:resume-game"));closeMenu();return}if(action==="logout"){event.preventDefault();try{localStorage.removeItem("steemFlagsAuthSession");localStorage.removeItem("steemFlagsPendingRewards");localStorage.removeItem("steemflags.username");sessionStorage.removeItem("steemFlagsSponsorContext");sessionStorage.removeItem("steemFlagsSponsorReward")}catch{}closeMenu();window.location.replace("./index.html?logout=1")}});
 document.addEventListener("click",e=>{if(!menu.hidden&&!menu.contains(e.target)&&!menuButton.contains(e.target))closeMenu()});window.addEventListener("languagechange",()=>{applyLanguage(menu,getLanguage());positionElements()});window.addEventListener("resize",positionElements);
}
